FROM kava/rocksdb:v8.10.1-go1.21 AS kava-builder

RUN apt-get update

WORKDIR /root/grbc
# Copy dependency files first to facilitate dependency caching
COPY ./go.mod ./
COPY ./go.sum ./

# Download dependencies
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    go version && go mod download

# Add source files
COPY . .

ARG grbc_database_backend=rocksdb
ENV GRBC_DATABASE_BACKEND=$grbc_database_backend

# Mount go build and mod caches as container caches, persisted between builder invocations
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    make install COSMOS_BUILD_OPTIONS=$GRBC_DATABASE_BACKEND


FROM ubuntu:22.04

RUN apt-get update \
    && apt-get install -y libsnappy1v5 libgflags2.2 zlib1g libbz2-1.0 curl jq \
    && rm -rf /var/lib/apt/lists/*

# copy rocksdb shared objects
COPY --from=kava-builder /usr/local/lib/ /usr/local/lib/
RUN ldconfig

# copy grbc binary
COPY --from=kava-builder /go/bin/grbc /bin/grbc

CMD ["grbc"]
